
schema_version = "1.0.0"
id = "timeline_buttons"
version = "1.0.0"
name = "Timeline Buttons"
tagline= "Put the buttons in timeline to other animation related editors, Affected Editors - Dopesheet Editor, Graph Editor, NLA Editor, Sequencer"
maintainer = "TinkerBoi <support@tinkerboi.com>"
type = "add-on"
website = "https://blendermarket.com/creators/tinkerboi"
tags = ["Animation"]
blender_version_min = "4.2.0"
license = [
  "SPDX:GPL-2.0-or-later",
]
